### ISSUE TITLE
Shell.py: Fix typo in L9

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2731] opened 2016-09-07 23:18 UTC
Inside the "docstring" in https://github.com/coala-analyzer/coala/blob/19b6e22edd093fee3f5eaa17c761007f47204a34/coalib/misc/Shell.py#L9

`surpresses` -->`suppresses`

**Comment by beatrix-bodo** [comment] 2016-09-09 11:49
@sils197 is this a duplicate of https://github.com/coala-analyzer/coala/issues/2484 ?

**Comment by sils1297** [comment] 2016-09-09 11:50
Yes, thanks!

**Closed by sils1297** 2016-09-09 11:50 UTC
Labels: difficulty/newcomer
