### ISSUE TITLE
run_tests.py hangs under certain circumstances

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#380] opened 2015-03-12 17:17 UTC
The iglob function is defined in coalib.parsing.glob.py and takes a *pattern* argument which should be a *string*. Printing this pattern at the beginning of the function should be entirely possible, but it causes the run_test.py Script to hang on the SectionManagerTest.

I pushed the issue on the branch glob_print_bug.

Please note that executing the SectionManagerTest on it's own works for me. 
Also, the run_tests.py script does *not* fail if I print an arbitrary string instead of the pattern variable.

Output if manually canceling the execution of run_tests.py when stalled:
> 43/51 | FunctionMetadataTest
 44/51 | SectionFillerTest
 45/51 | SectionManagerTest
^CTraceback (most recent call last):
  File "./run_tests.py", line 37, in <module>
    exit(testhelper.execute_python3_files(ignore_list))
  File "/home/fabian/Projekte/coala/coalib/tests/TestHelper.py", line 144, in execute_python3_files
    self.__execute_test(file, i+1, number, ",".join(ignore_list))
  File "/home/fabian/Projekte/coala/coalib/tests/TestHelper.py", line 132, in __execute_test
    result = self.__execute_python3_file(filename, ignored_files)  # either 0 or 1
  File "/home/fabian/Projekte/coala/coalib/tests/TestHelper.py", line 91, in __execute_python3_file
    return self.__print_output(["python3", filename])
  File "/home/fabian/Projekte/coala/coalib/tests/TestHelper.py", line 76, in __print_output
    retval = p.wait()
  File "/usr/lib64/python3.4/subprocess.py", line 1565, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.4/subprocess.py", line 1513, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib64/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by sils1297** [comment] 2015-03-12 17:19
Maybe our TestHelper can't handle large amounts of output, I'll try to reproduce with a minimal testcase.

**Comment by sils1297** [comment] 2015-03-12 17:24
I added a simple test:

```python
if __name__ == '__main__':
    for i in range(0, 100000):
        print("t")
```

And got the same results. So we get two possibilities IMO:

 * TestHelper can't handle too much output at all
 * TestHelper output processing makes the whole thing much slower than actually outputting it

Other clues/ideas?

**Comment by sils1297** [comment] 2015-03-12 17:27
Found something intriguing:

```python
if __name__ == '__main__':
    for i in range(0, 26628):
        print("t")  # DOESNT work
```

```python
if __name__ == '__main__':
    for i in range(0, 26627):
        print("t")  # DOES work
```

**Comment by smfn3321** [comment] 2015-03-12 17:28
I suspect it works for small numbers, so does it gradually get slower or break at one spedific amount?

**Comment by sils1297** [comment] 2015-03-12 17:28
it breaks at 26627/8

**Comment by sils1297** [comment] 2015-03-12 17:28
at least if one's printing "t\n"

**Comment by sils1297** [comment] 2015-03-12 17:29
actually depends on the chars printed I think

**Comment by smfn3321** [comment] 2015-03-12 17:30
where is the threshold for two chars?

**Comment by sils1297** [comment] 2015-03-12 17:33
```python
if __name__ == '__main__':
    for i in range(0, 53254):
        print("t", end="")
```

last thing that works, so 53254 chars it seems...

**Comment by smfn3321** [comment] 2015-03-12 17:33
which is 2 times 26627

**Comment by sils1297** [comment] 2015-03-12 17:34
exactly.

**Comment by sils1297** [comment] 2015-03-12 17:34
strange...

**Comment by sils1297** [comment] 2015-03-12 17:36
could you try if that holds true for your system also?

**Comment by sils1297** [comment] 2015-03-12 17:38
maybe it has something to do with process output buffers... just throwing things into the room...

**Comment by smfn3321** [comment] 2015-03-12 17:46
Confirmed:

statement | works
------------- | -------------
print("t", end="") | <= 53254

**Comment by smfn3321** [comment] 2015-03-12 18:55
Ok so it looks like this originates at the Linux kernel pipes, which have a limited capacity. Quoting http://bugs.python.org/issue8426:

>But, and that's the important point, both pipes and unix sockets have a limited capacity (used to be 4k - pagesize - on older Linux kernels for pipes, now it's 64k, and between 64k-120k for unix sockets, depending on tunable systcls).

It looks like we hit that 64k limit

**Comment by smfn3321** [comment] 2015-03-12 18:59
possibly useful for a workaround:

http://www.google.com/url?q=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F15137292%2Flarge-objects-and-multiprocessing-pipes-and-send&sa=D&sntz=1&usg=AFQjCNFw_xfP_fG4qVInHiJgzuNXDsEPew

http://www.google.com/url?q=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F16576386%2Fbyte-limit-when-transferring-python-objects-between-processes-using-a-pipe&sa=D&sntz=1&usg=AFQjCNFUdqw2dgGTwpZLNy6VxaRpkO5XFw

**Closed** 2015-07-01 09:46 UTC
Labels: bug, testing
