### ISSUE TITLE
Problems using SublimeText3 as text editor to open file with.

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#284] opened 2015-02-14 20:24 UTC
The file opened is empty and has a funny name (tmpfun1bz1vmain.cpp). File checked was main.cpp
Also something something with the locale setting seems off as opening ST3 normally doesn't yield the error.
vi and nano work.

![bildschirmfoto vom 2015-02-14 21 19 12](https://cloud.githubusercontent.com/assets/6530123/6200931/901e29bc-b48f-11e4-9dae-87f38fab71ad.png)

**Comment by sils1297** [comment] 2015-02-14 21:17
Duplicate of #278

**Closed** 2015-02-14 21:17 UTC

**Comment by sils1297** [comment] 2015-02-14 21:25
Solution:

Add --wait Argument for sublime.
Add -s Argument for gedit
