### ISSUE TITLE
dbus and munkres show up in coverage. (Mac)

### ISSUE THREAD

**Issue by Udayan12167** [coala-analyzer/coala#658] opened 2015-06-13 12:47 UTC
```
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/__init__                      19      4      4      2    74%   71, 77-78, 101
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/_compat                        3      0      0      0   100%   
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/_dbus                         63     24     20     15    53%   44, 93-98, 110-113, 121, 134, 145, 157, 162-171, 193, 229
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/_expat_introspect_parser      38     29     16     16    17%   32-35, 38-43, 46-54, 57-63, 82-85
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/_version                       2      0      0      0   100%   
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/bus                          133     78     39     37    33%   62-84, 93-98, 137-142, 151-158, 166-169, 172-184, 222-239, 252-253, 274-275, 328-331, 341-344, 355-359, 373, 383, 414, 428, 443
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/connection                   327    217    183    157    27%   43, 50, 61, 74, 76, 78, 93, 95, 109-122, 126, 130, 134, 142, 144, 146, 150-151, 158, 162, 166-178, 181-236, 239-242, 290, 312-326, 404-409, 430-456, 464-515, 519, 526-549, 564-611, 622, 625, 631, 633, 642-647, 658, 667
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/decorators                   109     65     57     41    36%   162-167, 172, 176, 178, 186, 188, 204, 207, 264-345
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/exceptions                    59     31     16     16    37%   46-52, 58-66, 70-74, 77-88, 91, 98, 105, 112, 119, 127, 134
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/lowlevel                       3      0      0      0   100%   
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/mainloop/__init__              9      0      0      0   100%   
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/proxies                      200    148     79     71    22%   30-31, 55-59, 62-70, 73, 85-101, 104-139, 148-161, 207-266, 363, 372-375, 386-388, 391-403, 406-418, 421-428, 431-440, 443-446, 471-484, 487, 509-513, 540-543, 547-550, 560-562, 565
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/service                      343    223    196    158    29%   58, 62, 65, 114-118, 123, 136-148, 174, 178, 181, 191-248, 252-268, 272-296, 327-353, 356-371, 459-460, 464, 482, 495-501, 511-517, 531, 557, 565, 571, 580-581, 585-586, 612, 615-619, 625, 631-632, 634-637, 643, 647-754, 762-782, 785-789, 826-835
/usr/local/Cellar/python-dbus/1.2.0/lib/python3.4/site-packages/dbus/types                          6      2      2      1    62%   13-14
/usr/local/lib/python3.4/site-packages/munkres                                                    252    209    126    125    12%   326-327, 345-365, 388-423, 427, 431-434, 441-450, 458-469, 477-490, 500-523, 536-559, 568-575, 579-585, 589-611, 618-624, 631-637, 644-650, 653-657, 661-663, 667-670, 706-709, 722-742, 750-786
bears/__init__                                                                                      0      0      0      0   100%   
bears/codeclone_detection/ClangASTPrintBear                                                        15      0      8      0   100%   
```

**Comment by sils1297** [comment] 2015-06-13 12:48
could you try if https://github.com/coala-analyzer/coala/pull/656 solves that?

**Comment by Makman2** [comment] 2015-06-13 14:22
I think this is duplicate of #621.

**Comment by sils1297** [comment] 2015-06-13 14:25
At least it has probably the same fix as mentioned.

**Comment by Makman2** [comment] 2015-06-16 17:05
@Udayan12167 try to run the coverage again on master, should be fixed now :)

**Comment by Udayan12167** [comment] 2015-06-17 06:18
I think because i am using homebrew to install everything it gets installed in the `/usr/local/Cellar` directory. We need to omit that too.

**Comment by sils1297** [comment] 2015-06-17 07:46
@Udayan12167 can you add that directory to the ignore list and make a PR if it works?

**Comment by AbdealiJK** [comment] 2015-06-25 16:02
Fixed in https://github.com/coala-analyzer/coala/commit/319c8a81c6351722e482d8e7675c7e9eaf378140

**Closed by AbdealiJK** 2015-06-25 16:02 UTC
Labels: platform dependent, testing
