### ISSUE TITLE
bears and dependencies

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#905] opened 2015-08-10 11:50 UTC
So, this is a slightly complicated thing to describe. But it's there in gnome-code-assistance

If we make the LinterBear - and make a bunch of Linters for .... example: python, c, ruby, go, css, html, etc. Each of these linters will have a different dependency - so, the "requirements" for coala would become huge - because every bear would be written in different things.

so, we need a better way to handle dependencies of bears.

The simplest solution is to make each bear into it's own package ?

**Comment by sils1297** [comment] 2015-08-10 11:53
I think each bear a package is really too much. I'd rather create
collections, like a "base" collection and some topic collections.

2015-08-10 13:50 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment] 2015-08-10 11:54
aaand lets use pip packages for that, I don't want to do a coala package
manager.

2015-08-10 13:53 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by AbdealiJK** [comment] 2015-08-10 11:56
Yes, obviously we'd be using pip :p
Collections makes sense - but then we'd have to categorize and all - not difficult (just saying)

**Comment by sils1297** [comment] 2015-09-01 11:11
kind of a duplicate of https://github.com/coala-analyzer/coala/issues/903

**Closed by sils1297** 2015-09-01 11:11 UTC
