### ISSUE TITLE
Add warning message if language not supported by Bear

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#2309] opened 2016-06-11 06:55 UTC
This is a feature proposal for Lint class. If a user runs GoErrCheckBear for a Python code, there's no warning of any sorts. With this implementation, I want to add a can_lint(bear,language) method which would at least warn the user that this bear is meant for Go code (by accessing the languages tuple of Lint class).

Also list out all the bears that the user could rather use to lint the files. (based on language of that filename)

**Comment by Makman2** [comment] 2016-06-12 00:55
the question is: what are python files? is the ending enough? I would say on first sight the user is responsible for handling this ^^

**Comment by sils1297** [comment] 2016-06-12 08:01
what's with python 2 vs. 3 e.g.? C or C++ header? ...

**Comment by AbdealiJK** [comment] 2016-06-12 08:07
Well, this detection may not be always accurate - and I don't think it can always be made accurate (Softwares like `magic` which identify the mimetype of files in Linux try doing this, and haven't been able to completely succeed - they fall back to file extension frequently).

**Comment by Makman2** [comment] 2016-06-12 16:48
okay, agreeing on "wontfix/not-happening"?

**Comment by sils1297** [comment] 2016-06-12 19:34
So we could check the `language` setting which bears should use consistently anyway if they support different languages. (Not sure if coalang bears do that niely right now.

**Comment by Makman2** [comment] 2016-06-12 21:04
what language setting? :O

**Comment by mr-karan** [comment] 2016-06-14 08:21
^ he means the languages tuple which we have in the Lint class, I think.

So, regarding accuracy I tried to use Linguist but failed as it's not supported for Py3. And it no way hinders the execution, it just displays a warning message.
 
On second thoughts the use case of this is also very low. So what do you suggest should I clean it up a bit more and move this code to a more generic place rather than Lint as @sils1297 suggested or is it `not happening/wont fix` and I should move on to my next Week's task? 

Ccing @manoranjanp as I need your views on this also.

**Comment by Makman2** [comment] 2016-06-14 17:12
the problem is still the mapping of "language-name" -> "is this file actually this language".

**Comment by sils1297** [comment] 2016-06-17 08:33
IMO we should trust the user that he does the right thing, detecting languages to check up on the user will most likely fail more often than succeed - wontfix/not happening IMO.

**Comment by sils1297** [comment] 2016-06-17 08:33
reopen if you disagree

**Closed by sils1297** 2016-06-17 08:33 UTC
