### ISSUE TITLE
test_show_bears failing

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2055] opened 2016-04-25 09:44 UTC
```
self = <tests.coalaTest.coalaTest testMethod=test_show_bears>

    def test_show_bears(self):
        retval, output = execute_coala(coala.main, "coala", "-A")
        self.assertEqual(retval, 0)
        lines = output.splitlines()
        bear_missing_lines = sum(1 for line in lines if "WARNING" in line)
>       self.assertEqual(bear_missing_lines, 0)
E       AssertionError: 11 != 0
```

**Comment by sils1297** [comment] 2016-04-25 13:23
This issue is due to other *installed* bears being malformatted and coala raising a warning for them.

**Comment by Makman2** [comment] 2016-04-25 19:23
oh I thought this was because of misconfiguration on my system, good then it's confirmed :)

**Comment by sils1297** [comment] 2016-04-25 19:24
We should fix the bears *and* make the test immune.

**Comment by AbdealiJK** [comment] 2016-04-26 01:32
Hmmmm. I'll think about this and see if I can do something

**Comment by AbdealiJK** [comment] 2016-04-26 01:33
I think this can be fixed by simply using the `with bear_test_module():` as that forces the bear_tests only to be found

**Closed** 2016-04-26 09:32 UTC
Labels: type/bug, type/test
