### ISSUE TITLE
argparse: Use action instead of nargs and metavar for optional positional arguments

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2098] opened 2016-04-30 15:09 UTC
Now, when I run `--help` I get something like:
```
  -A [BOOL], --show-all-bears [BOOL]
                        Display all bears.
```
I think it would be much nicer to have it like
```
  -A, --show-all-bears  Display all bears.
```
This can be achieved by using `action='store_true'` for optional arguments instead of `nargs` and `metavar` in `add_argument` function, when creating arg parser.

**Comment by AbdealiJK** [comment] 2016-04-30 15:26
This has been discussed, we can't do that because then when doing `--save` that "default" boolean value will be saved also (although it shouldn't as the user didn't specify it)

Note: This is not specifically for --show-all-bears, but in general. Possibly we could delete the --show-all-bears, etc (Which are handled separately) before it gets to the saving part ?

**Comment by Uran198** [comment] 2016-05-01 12:59
We can use what we use for bears parameters and I think to make something like `-A` or `-B` look nicer wouldn't be a lot of work.

**Comment by sils1297** [comment] 2016-06-03 01:54
duplicate of https://github.com/coala-analyzer/coala/issues/2228 which is currently being worked on

**Closed by sils1297** 2016-06-03 01:54 UTC
Labels: difficulty/low
