### ISSUE TITLE
Log messages can go in the same line as 'Please enter the number of the action' prompt

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2755] opened 2016-09-14 00:03 UTC
I saw something like this on @chauffer's monitor today:

```
|    | Please enter the number of the action you want to execute (Ctrl-D to exit). [ERROR] NLTK needs some data yadda yadda
```

The log messages should probably go on a new line somehow.

**Comment by sils1297** [comment] 2016-09-14 06:15
dupe of https://github.com/coala-analyzer/coala/issues/462

**Closed by sils1297** 2016-09-14 06:15 UTC
