### ISSUE TITLE
Add shorter links into docs

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1981] opened 2016-03-30 19:30 UTC
@sils1297 made some amazingly short URLs to use in the docs, aka http://tinyurl.com/coala-low which shows all low difficulty bugs &   http://tinyurl.com/coala-new which shows all newcomer bugs.

**Comment by sils1297** [comment] 2016-03-30 19:31
duplicate of two issues I'm filing right now

**Comment by sils1297** [comment] 2016-03-30 19:32
https://github.com/coala-analyzer/coala/issues/1982 and https://github.com/coala-analyzer/coala/issues/1980

**Closed by sils1297** 2016-03-30 19:31 UTC
Labels: area/documentation
