### ISSUE TITLE
IndexError with a Python module ending with "ignore =..."

### ISSUE THREAD

**Issue by AndreaCrotti** [coala-analyzer/coala#2563] opened 2016-07-25 15:02 UTC
A simple Python file with a line like this:

ignore = 'ignore'

and nothing generates this exception launching this command:

```
coala --files=simplefile.py --bears=SpaceConsistencyBears -S use_spaces=True --verbose
```

```
[DEBUG][15:59:55] Exception was:
Traceback (most recent call last):

  File "/home/andrea/.local/lib/python3.4/site-packages/coalib/coala_main.py", line 91, in run_coala
    log_printer=log_printer)

  File "/home/andrea/.local/lib/python3.4/site-packages/coalib/processes/Processing.py", line 697, in execute_section
    log_printer),

  File "/home/andrea/.local/lib/python3.4/site-packages/coalib/processes/Processing.py", line 526, in process_queues
    ignore_ranges = list(yield_ignore_ranges(file_dict))

  File "/home/andrea/.local/lib/python3.4/site-packages/coalib/processes/Processing.py", line 460, in yield_ignore_ranges
    len(file[line_number])))

IndexError: tuple index out of range

```

it's probably just assuming there are more lines after which is not always the case.
I'm not sure why it happens only with ignore though, is it correct that it's handled differently since it's not a directive for coala anyway?

**Comment by sils1297** [comment] 2016-07-25 15:39
Hey, most of the team is boarding planes right now. Maybe @Asnelchristian or @mr-karan can look at this?

Otherwise it'll take a few hours longer for initial investigation :/

**Comment by sils1297** [comment] 2016-07-25 15:39
Oh @Makman2 is done with exams, ping?

**Comment by Makman2** [comment] 2016-07-25 15:46
confirmed

**Comment by sils1297** [comment] 2016-07-25 16:11
This should be fixed for this release.

**Comment by sils1297** [comment] 2016-07-25 16:11
Get fixed, I mean

**Comment by sils1297** [comment] 2016-07-25 19:58
Cool, so we can simplify this and hopefully merge something by tomorrow easily. @Asnelchristian can you review @Makman2 s PR later when he reiterates on it?

**Comment by sils1297** [comment] 2016-07-25 19:58
My plane takes off soon so I won't be able to review for a bit.

**Comment by AndreaCrotti** [comment] 2016-07-26 08:47
Thanks for the really quick response!

**Closed** 2016-07-26 21:31 UTC
Labels: process/wip

**Comment by sils1297** [comment] 2016-07-26 21:33
Hey @AndreaCrotti a bugfix was merged: you can use the latest development version by running `pip install coala coala-bears --pre`. I guess there will be a release somewhen in the next week or so though I'm barely around which means it might also take longer.

**Comment by AndreaCrotti** [comment] 2016-08-01 09:44
Thanks @sils1297 thanks a lot (and no rush of course for the release).

Anyway just one thing, in the actual fix I've seen something like

```
		 +        # This case was a bug.
                 +        test_file_dict_single_line = {'f': ('# ignore XBEAR',)}
```

which however is not the same as I was pointing out.
The same problem also happened with something like

```
ignore = 'ignore'
```

which I think should not be analysed at all from Coala.
Is that correct that Coala also checks for things to ignore outside of comments?
thanks!

**Comment by sils1297** [comment] 2016-08-01 10:40
Hi,

coala has no understanding of the programming language below. Thus it won't care if something is in a comment or not!

If you think about it, the false positive risk is pretty low. If you have something like `ignore PyLintBear` in your code it's unlikely that you mean something else. The statement `ignore = 'ignore'` won't do anything because there's no such bear as `ignore` :)

**Comment by sils1297** [comment] 2016-08-01 10:47
Actually we do have a false positive risk here because the ignore statements support globs. One could do `ignore = 'something,*,'` and coala would ignore all results for this and the following line, the `*` has to be enclosed within commas/spaces for that to happen. If you have any sane idea on how to avoid this, I'd be happy to hear it.

Reading comments only might be possible at least for some languages and we'd fall back to "dumb mode" for the others... but that's pretty complicated from a coala PoV though certainly doable.

**Comment by AndreaCrotti** [comment] 2016-08-01 15:47
Ahh ok I kind of assumed that there was more information about what was being parsed..
Anyway probably not a bug that is very likely to happen I guess in this case.
