### ISSUE TITLE
Ignore doesn't work

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1232] opened 2016-01-22 10:40 UTC
I have no idea why but at https://gitlab.com/gitmate/IGitt/merge_requests/5/diffs#c2a0be4162a3742a2be747607029e0ea9121a1d0_0_41 the ignore doesn't seem to work.

Can somebody try to reproduce this?

**Comment by AbdealiJK** [comment] 2016-02-14 04:09
@sils1297 this doesnt seem to be a bug
I tried recreating it and the `Ignore` didnt work because the diff was only on line 42
So, you need to do `old_major, old_minor, old_micro = map(int, old_version[:3]) # Ignore PyLintBear`

But as that is too long (> 80 chars), so you can do: 
```
    old_major, old_minor, old_micro = map(  # Ignore PyLintBear
        int, old_version[:3])
```
which also works - I tested

Closing this - reopen if you face it again.

**Comment by sils1297** [comment] 2016-02-15 09:18
apparently @WJCode has this too

**Comment by WJCode** [comment] 2016-02-15 09:26
@sils1297 @AbdealiJK I'm able to reproduce this issue with some code I was using. Sample below. 
The `start ignoring`, `stop ignoring` keywords seem to work correctly.
```
"""
This script is just meant to test the functionality of ignore
"""

# Ignore PyLintBear
def foo(query_response):
    """
    This function is meant to test PyLintBear
    """
    # Ignore LineLengthBear
    save_url = query_response.split('<div class="nxtUrl"> ')[1].split('<a href="')[1].split('"')[0]
    print(save_url)
    # Ignore LineLengthBear
    save_description = query_response.split('id="desc-nohtml-maxlen"></div>')[1].split("<")[0]

    return (save_url, save_description)

# start Ignoring LineLengthBear
unwrappable_string = "A long lengthy string that is also long and would exceed the limit "
# stop ignoring

```

**Comment by sils1297** [comment] 2016-02-15 09:44
so the `ignore *bear*` statement is only valid for two lines, the line where it stands and the following. coala is not aware of scopes or so!

**Comment by WJCode** [comment] 2016-02-15 12:49
Got it. I see this in the code too. Actually, I had added that first `# Ignore PyLintBear` because it seems that `foo` is a black listed name :)
```
|   6| def foo(query_response):
|    | [INFO] PyLintBear:
|    | C0102 - Black listed name "foo"
```

**Comment by WJCode** [comment] 2016-02-15 12:49
I see a potential issue and a little clarification is needed regarding `TextRange`. We have TextRange(start, end) where start & end are (line, column) pairs.
Assume values for a TextRange as (1,None,2,None) so does this mean that the TextRange is the entire 1st line and the entire 2nd line? This seems to be how the code currently deals with it

**Comment by Makman2** [comment] 2016-02-15 20:39
@WJCode it does, but this is intended by design. I think that's quite clear, "from line 1 to line 2" :+1:

**Comment by AbdealiJK** [comment] 2016-02-16 11:38
Um ... so, @WJCode 's code also works as expected - I think this issue can be closed again

**Comment by Makman2** [comment] 2016-02-16 17:33
@WJCode so is the "ignore"-bug fixed for you? If you have still concerns about the `TextRange` stuff please open a new issue :)

**Comment by WJCode** [comment] 2016-02-17 18:19
@Makman2 @AbdealiJK, Sorry about the late response I was working :disappointed: . I still see the issue in the code above even after a rebase(in case I missed any new changes).

I'm trying to do some more digging to see how values come down from `SourceRange` to `TextRange.overlaps()`

Currently, `TextRange.overlaps()` doesn't seem to deal with `None`s. For example:
```
        uut1 = TextRange.from_values(1, None, 2)
        uut2 = TextRange.from_values(2, 81, 2, 91)
        self.assertTrue(uut1.overlaps(uut2))              # is False
        self.assertTrue(uut2.overlaps(uut1))              # also False
```
This test corresponds to this input:
```
# Ignore LineLengthBear
unwrappable_string = "First lengthy string that is a bit long and would exceed the limit "
```
I am now trying to understand how the values(especially column values) are coming down to `TextRange` from the `SourceRange` and if those values can be set without breaking other stuff.

**Closed** 2016-02-24 21:39 UTC
Labels: area/core, difficulty/medium, importance/high, type/bug
