### ISSUE TITLE
Update instructions on setting up coala in a virtualenvironment

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1271] opened 2016-02-03 09:35 UTC
Should we prefer if contributors use `virtualenv` ? That way this ensures that those contributing to coala have a fixed set of requirements without cluttering their global `pip3`

**Comment by sils1297** [comment] 2016-02-03 09:39
duplicate of https://github.com/coala-analyzer/coala/issues/1017

**Closed by sils1297** 2016-02-03 09:39 UTC
Labels: status/duplicate
