### ISSUE TITLE
package.json: Use in continuous integration

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1355] opened 2016-02-09 17:06 UTC
Since we have now a `package.json` file for `npm` dependencies we should integrate that into our CI.
Would be nice to have that also for windows/appveyor.

**Comment by sils1297** [comment] 2016-02-09 17:07
duplicate of https://github.com/coala-analyzer/coala/issues/1351 - why is this medium anyway? Should be simple to do...

**Closed by sils1297** 2016-02-09 17:07 UTC
Labels: difficulty/medium, type/CI
