### ISSUE TITLE
Tests fail with .coarc

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2142] opened 2016-05-14 12:22 UTC
`~/.coarc`:

```
[Default]
files = *.py
max_line_length = 80
```

Tests failing: `coalaTest`, `ConfigurationGatheringTest`

**Comment by sils1297** [comment] 2016-05-14 12:23
using `-I`

**Comment by sils1297** [comment] 2016-05-14 12:26
...should solve that issue :P

**Comment by Makman2** [comment] 2016-05-14 13:56
This could be a duplicate of https://github.com/coala-analyzer/coala/issues/2111

**Comment by Makman2** [comment] 2016-05-14 13:58
@sils1297 and how does using `-I` solve that? You can't pass `-I` through py.test, or do you mean to change the coala arguments inside the tests?

**Comment by sils1297** [comment] 2016-05-14 14:55
Inside the tests

**Comment by sils1297** [comment] 2016-06-13 16:55
still valid?

**Comment by Makman2** [comment] 2016-06-13 19:56
nope :)

**Closed by Makman2** 2016-06-13 19:56 UTC
Labels: area/tests, difficulty/low, type/bug
