### ISSUE TITLE
Windows: coala doesn't find coala-bears

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1831] opened 2016-03-06 23:40 UTC
Installed/upgraded stuff as usual: (On Windows pip3 = pip)
`pip install coala coala-bears --upgrade --pre`
Installing succeeds, but using this coafile on coala-tutorial:
```
[Default]
bears = SpaceConsistencyBear
files = src/*.c
use_spaces = yeah
```
Says
```
D:\Users\MAK\Eigene Dokumente\GitHub\coala-tutorial [master +1 ~0 -0 !]> coala
[WARNING][00:39:30] No bears were found matching 'SpaceConsistencyBear'.
Executing section Default...
```
as you can see git is dirty, but that's only the .coafile:
```
D:\Users\MAK\Eigene Dokumente\GitHub\coala-tutorial [master +1 ~0 -0 !]> git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .coafile

nothing added to commit but untracked files present (use "git add" to track)
```

Can anyone confirm this?

**Comment by Makman2** [comment] 2016-03-06 23:43
Btw that's for Windows 10, either `cmd`, `powershell` or the GitHub app's git-shell.

**Comment by AbdealiJK** [comment] 2016-03-07 01:58
Hey, does pytest work for you on windows ? (I ask because this would ensure that custom entry-points works fine there)
Second: Can you run `collect_registered_bears_dirs('coalabears')` and check the output ? print out things inside the loop and check which all eps are being found by `pkg_resources`

**Comment by Makman2** [comment] 2016-03-07 18:49
1.
py.test does work (though some tests fail in coala-bears and coala, but that's because of my machine).

2.
```
>>> from coalib.collecting.Collectors import collect_registered_bears_dirs as crbd
>>> crbd
<function collect_registered_bears_dirs at 0x030D07C8>
>>> crbd('coalabears')
['D:\\Program Files (x86)\\Python 3.4.3\\lib\\site-packages\\bears']
```
The path is valid, inside this one all bears are located :+1:

**Comment by AbdealiJK** [comment] 2016-03-08 03:18
next thing is to print the function `bear_dirs()` in Section and make sure it has a glob using this path in the list it returns.

If it does, next would be to check that the globbing modules `icollect_bear()` finds things inside this directory.

**Comment by Makman2** [comment] 2016-03-08 18:03
For `bear_dirs()`:
```
['d:\\program files (x86)\\python 3.4.3\\lib\\site-packages\\bears\\**']
```

But indeed `icollect_bears()` fails:
```
D:\Users\MAK\Eigene Dokumente\GitHub\coala [master +3 ~0 -0 !]> python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from coalib.collecting.Collectors import icollect_bears
>>> from coalib.bears.BEAR_KIND import BEAR_KIND
>>> paths = ['d:\\program files (x86)\\python 3.4.3\\lib\\site-packages\\bears\\**']
>>> from pyprint.NullPrinter import NullPrinter
>>> list(icollect_bears(paths, ["**"], [BEAR_KIND.LOCAL, BEAR_KIND.GLOBAL], NullPrinter()))
[]
>>>
```

**Comment by AbdealiJK** [comment] 2016-03-09 01:20
Sooo ... that's not expected behaviour in icollect ... can you go into it
and debug ?

**Comment by hypothesist** [comment] 2016-03-13 16:55
@Makman2 can you test whether you can reproduce the bug if there are no whitespaces in the coala-bears, coala, **and** the test project location?

**Comment by hypothesist** [comment] 2016-03-13 16:56
I suspect this _might_ be related to https://github.com/coala-analyzer/coala/issues/1613

**Comment by Makman2** [comment] 2016-03-15 02:24
@hypothesist it is indeed! Just tested on your PR https://github.com/coala-analyzer/coala/pull/1644 and bears are found instantly. So this one is solved when https://github.com/coala-analyzer/coala/pull/1644 is merged :+1:

**Comment by AbdealiJK** [comment] 2016-03-16 06:02
Assigning to hypothesist as he's working on it.

**Closed** 2016-03-25 10:12 UTC
Labels: importance/high, type/bug
