### ISSUE TITLE
Convention: asserts vs. valueerror

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#983] opened 2015-10-11 17:47 UTC
We do some value checks here and there, e.g. if a comparison with a weird object happens we throw an exception. There are two major candidates for that:

# AssertionError

That's the awesome one: just `assert some_expression, "message"`

# ValueError

```python
if some_expression:
    raise ValueError("message")
```

As pointed out I'm heavily in favor of the first one because it's much shorter.

@Makman2 your opinion?

**Comment by Makman2** [comment] 2015-10-11 17:52
I do like `ValueError` because it shows more what's wrong and imo the usage of an `AssertionError` belongs to cases where you test inner behaviour and not make user-sanity checks^^
Also I haven't seen any `AssertionError` from a builtin/3rd-party library, but many `ValueError`s.

Citing python docs:
> Assert statements are a convenient way to insert debugging assertions into a program:

It's for debugging purposes, not for runtime purposes^^

**Comment by sils1297** [comment] 2015-10-11 17:55
@Makman2 well those errors are programmer errors and are intended for debugging! If a programmer compares 4 with a SourceRange he's stupid and that's what the assertion is for.

**Comment by Makman2** [comment] 2015-10-11 22:28
but well the programmer "uses" our code. And even in runtime stupid things can happen that are never intended to happen at all.
I mean a real user that doesn't program a lot and uses our software (very interesting case, but anyway) can't even do something with a ValueError, so there's no difference using an AssertionError and a ValueError (or other exception) except the semantical thing. AssertionError = some assert the programmer/user doesn't know and need to lookup anyway failed, ValueError = The fed in value for the property/function does not fit -> I need to reread the docs and feed in something else.

**Comment by sils1297** [comment] 2015-10-12 09:19
> AssertionError = some assert the programmer/user doesn't know and need to lookup anyway failed, ValueError = The fed in value for the property/function does not fit -> I need to feed in something else and maybe reread the docs if necessary.

Translation:

AssertionError: The programmer needs to do something.
ValueError: The user needs to do something.

In those cases the programmer needs to do something, don't blame the user for the programmers fault.

**Comment by AbdealiJK** [comment] 2015-10-12 09:23
From the docs of python:
*exception *ValueError - Raised when a built-in operation or function
receives an argument that has the right type but an inappropriate value,
and the situation is not described by a more precise exception such as
IndexError
<https://docs.python.org/2/library/exceptions.html#exceptions.IndexError>.

So, if a programmer compares SourceRange with a 4, shouldn't it be a
TypeError ?

**Comment by sils1297** [comment] 2015-10-12 11:21
@AbdealiJK @Makman2 for what would you then use assertions?

Quote from SO:

> Asserts should be used to test conditions that should never happen. The purpose is to crash early in the case of a corrupt program state.

The advantage of asserts is that they're short. We want the program to fail early (i.e. before the user gets it) when the programmer does something wrong. Assertions provide a way to do that. If we now require the developer to make an if condition and a raise with the appropriate error this gets more complicated and people like me will try to *avoid* writing those because they're verbose, they need an extra test case and they are *not expected to happen*.

Assertions are for programmers. Exceptions are for errors that appear on runtime. In python this is a bit mixed up because assertions *are* exceptions but still I think we should follow this philosophy and thus use assertions for those cases. They are programmer errors.

**Comment by AbdealiJK** [comment] 2015-10-12 11:29
Well, assertions seem to be something that are just there for developers of
the code itself.

In fact, all assert statements are removed when you run python with
optimization says this post
http://programmers.stackexchange.com/questions/225956/python-assert-vs-if-return

You'd normally run it with optimization if you're in a production
environment - like windows binary or even in ubuntu. (Currently we do not
do that though)

To quote one of the answers:
assert is most useful in situations like, "I want to helpfully work around
this problem if a user hits it, but if a developer hits it, I want it to
crash hard so he will fix the code that calls this function incorrectly."

So, there's no hard rule about when to use ValueError/TypeError vs assert -
it depends on every case

**Comment by Makman2** [comment] 2015-10-12 20:37
@AbdealiJK sure in the current example it should be a `TypeError` and no `ValueError` :)

@sils1297
> Assertions are for programmers. Exceptions are for errors that appear on runtime. In python this is a bit mixed up because assertions are exceptions but still I think we should follow this philosophy and thus use assertions for those cases. They are programmer errors.

Even that's the reason not to use `AssertionError`, like @AbdealiJK stated with

> In fact, all assert statements are removed when you run python with optimization says this post

The model/idea behind assertions is not raising a runtime exception (python does it anyway because it's the python way), but tracking just bugs in developing/debug stage internally.

> Asserts should be used to test conditions that should never happen. The purpose is to crash early in the case of a corrupt program state.

This isn't applicable any more if asserts are stripped^^

Also you have the same test overhead since you need to test if an `AssertionError` is raised.
Also it's minimal code to raise a custom exception.

```
if fail_condition:
    raise ValueError("bad...")
```

Other languages like C++ disable their assertions when releasing the code. So it's meant for tracking internal problems, not problems caused by the programmer/user using the library/program/whatever. If you want to say in C++ "this is wrong input and needs to be try-catched" then you raise an exception and don't make an assert normally if you create a library (like we do in fact).

So I believe the python assert was inspired from other languages (like C++), so I think we shouldn't use `AssertionError` for interfaces to the programmer/user.

**Comment by sils1297** [comment] 2015-10-20 15:13
@Makman2 would you mind writing down in the code style to use enforce_signature? With that I think we can close this.

**Comment by sils1297** [comment] 2015-10-20 15:16
Never mind, doing this now.

**Comment by Makman2** [comment] 2015-10-20 18:47
Since `enforce_signature`, that uses `TypeError` instead of `AssertionError`, is implemented and documented --> closing this issue.

**Closed by Makman2** 2015-10-20 18:47 UTC
Labels: codestyle
